#!/usr/bin/env bash
# assemble-context.sh — SessionStart hook
#
# Builds .brain/_CONTEXT.md from:
#   - latest N session summaries
#   - open decisions (status: proposed)
#   - open bugs (status: open)
#   - god-nodes section from .brain/graph/GRAPH_REPORT.md (if Graphify ran)
#   - pointers to CKIS vault
#
# Records session start state to .brain/.session-state for the Stop hook.
# Emits the assembled context to stdout (Claude Code injects it into the session).

set -euo pipefail

# Resolve repo root from this script's location.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

# shellcheck disable=SC1091
source "$REPO_ROOT/.brain/config.sh"

NOW="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
NOW_LOCAL="$(date +"%Y-%m-%d %H:%M %Z")"
HEAD_SHA="$(git rev-parse --short HEAD 2>/dev/null || echo "no-git")"
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "no-git")"

# Record session-start state for the Stop hook.
mkdir -p "$BRAIN_DIR"
cat > "$SESSION_STATE" <<EOF
SESSION_START_UTC="$NOW"
SESSION_START_LOCAL="$NOW_LOCAL"
SESSION_START_SHA="$HEAD_SHA"
SESSION_START_BRANCH="$BRANCH"
EOF

# Rotate any orphaned active log from a previous crashed/killed session.
# (Stop hook normally consumes _active.md; if it never ran, preserve the data.)
ACTIVE_LOG="$SESSIONS_DIR/_active.md"
if [ -f "$ACTIVE_LOG" ]; then
  mkdir -p "$SESSIONS_DIR"
  mv "$ACTIVE_LOG" "$SESSIONS_DIR/_orphaned-$(date +%Y-%m-%d-%H%M).md" 2>/dev/null || true
fi

# Rotate orphaned compact-triggers (from a session that never reached Stop).
COMPACT_TRIGGERS="$BRAIN_DIR/.compact-triggers"
if [ -f "$COMPACT_TRIGGERS" ]; then
  mkdir -p "$SESSIONS_DIR"
  mv "$COMPACT_TRIGGERS" "$SESSIONS_DIR/_orphaned-compacts-$(date +%Y-%m-%d-%H%M).log" 2>/dev/null || true
fi

# Sync GRAPH_REPORT.md into the CKIS vault (catch-up in case post-commit hook missed it).
bash "$REPO_ROOT/.brain/scripts/sync-graph-to-vault.sh" >/dev/null 2>&1 || true

# Build _CONTEXT.md.
{
  echo "---"
  echo "type: project-context"
  echo "project: $PROJECT_SLUG"
  echo "generated: $NOW"
  echo "branch: $BRANCH"
  echo "head: $HEAD_SHA"
  echo "tags: [context, brain, $PROJECT_SLUG]"
  echo "---"
  echo
  echo "# $PROJECT_NAME — Session Context"
  echo
  echo "> Auto-generated by \`.brain/scripts/assemble-context.sh\` at session start."
  echo "> Do not hand-edit. Update sources in \`.brain/decisions/\`, \`.brain/bugs/\`, or \`.brain/sessions/\`."
  echo
  echo "**Branch:** \`$BRANCH\` · **HEAD:** \`$HEAD_SHA\` · **Started:** $NOW_LOCAL"
  echo
  echo "━━━"
  echo
  echo "## CKIS pointers"
  echo
  echo "- Live business state → \`$CKIS_MEMORY\`"
  echo "- Project overview (curated) → \`$CKIS_PROJECT_OVERVIEW\`"
  echo "- Architecture spec → \`$CKIS_ARCHITECTURE_NOTE\`"
  echo
  echo "━━━"
  echo
  echo "## Recent sessions (last $RECENT_SESSIONS_LIMIT)"
  echo
  if compgen -G "$SESSIONS_DIR/*.md" > /dev/null; then
    # Newest first, take N.
    mapfile -t recent < <(ls -1t "$SESSIONS_DIR"/*.md 2>/dev/null | head -n "$RECENT_SESSIONS_LIMIT")
    for f in "${recent[@]}"; do
      echo "### $(basename "$f" .md)"
      echo
      cat "$f"
      echo
      echo "---"
      echo
    done
  else
    echo "_No prior sessions logged yet._"
    echo
  fi

  echo "━━━"
  echo
  echo "## Open decisions"
  echo
  if compgen -G "$DECISIONS_DIR/*.md" > /dev/null; then
    found=0
    for f in "$DECISIONS_DIR"/*.md; do
      [ "$(basename "$f")" = "README.md" ] && continue
      # Match `status: proposed` in frontmatter.
      if awk '/^---$/{c++} c==1 && /^status:[[:space:]]*proposed/{print; exit}' "$f" | grep -q proposed; then
        title="$(awk '/^# /{sub(/^# /,""); print; exit}' "$f")"
        [ -z "$title" ] && title="$(basename "$f" .md)"
        echo "- [$title]($f)"
        found=1
      fi
    done
    [ "$found" = "0" ] && echo "_No open decisions._"
  else
    echo "_No decisions logged yet._"
  fi
  echo

  echo "━━━"
  echo
  echo "## Open bugs"
  echo
  if compgen -G "$BUGS_DIR/*.md" > /dev/null; then
    found=0
    for f in "$BUGS_DIR"/*.md; do
      [ "$(basename "$f")" = "README.md" ] && continue
      if awk '/^---$/{c++} c==1 && /^status:[[:space:]]*open/{print; exit}' "$f" | grep -q open; then
        title="$(awk '/^# /{sub(/^# /,""); print; exit}' "$f")"
        [ -z "$title" ] && title="$(basename "$f" .md)"
        echo "- [$title]($f)"
        found=1
      fi
    done
    [ "$found" = "0" ] && echo "_No open bugs._"
  else
    echo "_No bugs logged yet._"
  fi
  echo

  echo "━━━"
  echo
  echo "## Code graph (Graphify)"
  echo
  REPORT="$GRAPH_DIR/GRAPH_REPORT.md"
  if [ -f "$REPORT" ]; then
    # Inline only the "God nodes" or "Surprising connections" section, capped.
    awk '
      /^## (God nodes|Surprising connections|Suggested questions)/ { keep=1; print; next }
      keep && /^## / { keep=0 }
      keep { print }
    ' "$REPORT" | head -n 80
    echo
    echo "_Full graph report: \`$REPORT\`_"
  else
    echo "_Graphify has not run yet. Run: \`graphify .\` then \`graphify hook install\`._"
  fi
  echo
} > "$CONTEXT_FILE"

# Emit to stdout so the SessionStart hook injects it as context.
cat "$CONTEXT_FILE"
